language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js: 8
before_install:
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
